import Link from "next/link"
import { ArrowRight, Percent, ShieldCheck, Truck } from "lucide-react"
import { getDeals } from "backend/services/recommendation.service"
import { getStoreContext } from "@/lib/store-context.server"
import { getProductImage as getProductImageForIndustry } from "@/constants/productImages"
import { getStoreRouteHref } from "@/lib/store-home"

export default async function DealsPage() {
	const store = await getStoreContext()
	const getProductImage = (image: string | undefined, name: string) => getProductImageForIndustry(image, name, store.industry?.slug)
	const deals = store.isPlatformHome ? [] : await getDeals(store.tenantId, 24).catch(() => [])

	return <div className="space-y-10"><section className="glass-card rounded-3xl p-6 text-center sm:p-8 md:p-12"><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-primary/10 px-4 py-2 text-sm font-medium text-primary"><Percent size={16} />Current store deals</div><h1 className="mb-4 text-3xl font-bold md:text-5xl">Savings from {store.brand.name}</h1><p className="mx-auto max-w-2xl text-gray-600 dark:text-gray-300">These offers are controlled by this merchant and reflect products currently marked with a sale price.</p></section>

		{deals.length === 0 ? <section className="glass-card p-8 text-center"><h2 className="text-xl font-bold">No active deals right now</h2><p className="mt-2 text-gray-600 dark:text-gray-300">This store has not published any products with a sale price yet. Please check back later.</p><Link href={getStoreRouteHref(store, "/products")} className="btn-primary mt-6 inline-flex items-center gap-2">Browse products <ArrowRight size={16} /></Link></section> : <section className="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-3">{deals.map((deal) => <article key={deal.id} className="glass-card flex h-full flex-col overflow-hidden p-0"><div className="product-media relative flex aspect-[4/3] items-center justify-center overflow-hidden"><img src={getProductImage(deal.images[0], deal.name)} alt={deal.name} className="h-full w-full object-contain transition-transform duration-300 hover:scale-105" /></div><div className="flex flex-1 flex-col p-6"><span className="mb-3 inline-flex w-fit rounded-full bg-accent/10 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-accent">On sale</span><h2 className="text-xl font-bold">{deal.name}</h2><p className="mt-2 text-sm text-gray-600 dark:text-gray-300">{deal.brand} · {deal.category}</p><div className="mt-4 flex items-baseline gap-2"><span className="text-xl font-bold text-primary">KES {(deal.discountedPrice ?? deal.price).toLocaleString()}</span><span className="text-sm text-gray-400 line-through">KES {deal.price.toLocaleString()}</span></div><Link href={getStoreRouteHref(store, `/products/${deal.slug}`)} className="mt-auto inline-flex items-center gap-2 pt-6 font-semibold text-primary hover:underline">Shop the deal <ArrowRight size={16} /></Link></div></article>)}</section>}

		<section className="grid grid-cols-1 gap-6 md:grid-cols-3"><div className="glass-card rounded-2xl p-6"><Truck className="mb-4 text-primary" size={28} /><h3 className="mb-2 text-lg font-semibold">Merchant-confirmed delivery</h3><p className="text-sm text-gray-600 dark:text-gray-300">Delivery terms and availability are confirmed directly by {store.brand.name}.</p></div><div className="glass-card rounded-2xl p-6"><ShieldCheck className="mb-4 text-primary" size={28} /><h3 className="mb-2 text-lg font-semibold">Store-managed warranty</h3><p className="text-sm text-gray-600 dark:text-gray-300">The merchant provides the applicable warranty, returns, and after-sales terms.</p></div><div className="glass-card rounded-2xl p-6"><Percent className="mb-4 text-primary" size={28} /><h3 className="mb-2 text-lg font-semibold">Live store pricing</h3><p className="text-sm text-gray-600 dark:text-gray-300">Offers update when the merchant changes product pricing in the admin panel.</p></div></section>
	</div>
}
