"use client"
import { useEffect, useState } from "react"
import { Search } from "lucide-react"
export default function AdminMessagesPage() {
	const [search, setSearch] = useState(""); const [tickets, setTickets] = useState<any[]>([]); const [selected, setSelected] = useState<any>(null); const [reply, setReply] = useState(""); const [error, setError] = useState("")
	const load = () => fetch(`/api/support/tickets?limit=100&search=${encodeURIComponent(search)}`, { cache: "no-store" }).then((r) => r.ok ? r.json() : Promise.reject(new Error("Unable to load messages"))).then((data) => setTickets(data.tickets || [])).catch((e) => setError(e.message))
	useEffect(() => { load() }, [search])
	const sendReply = async () => { if (!selected || !reply.trim()) return; const response = await fetch(`/api/support/tickets/${selected.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reply }) }); if (!response.ok) setError("Unable to send reply"); else { setReply(""); load() } }
	return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Messages</h1><p className="mt-1 text-gray-500">Support contact messages backed by support tickets.</p></div>{error && <p className="text-sm text-red-500">{error}</p>}<div className="glass-card flex items-center gap-3 p-4"><Search className="text-gray-400" size={18}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search messages" className="w-full bg-transparent outline-none"/></div><div className="grid gap-6 lg:grid-cols-[1fr_380px]"><div className="glass-card divide-y">{tickets.map((ticket) => <button key={ticket.id} onClick={() => setSelected(ticket)} className="block w-full p-4 text-left hover:bg-black/5"><div className="flex justify-between gap-3"><p className="font-medium">{ticket.subject}</p><span className="text-xs capitalize text-gray-500">{String(ticket.status).replaceAll("_", " ")}</span></div><p className="text-sm text-gray-500">{ticket.customerName} · {ticket.customerEmail}</p><p className="mt-1 line-clamp-2 text-sm">{ticket.description}</p></button>)}{!tickets.length && <p className="p-10 text-center text-gray-500">No messages found.</p>}</div><div className="glass-card min-h-60 p-5">{selected ? <><div className="mb-4"><h2 className="font-semibold">{selected.subject}</h2><p className="text-sm text-gray-500">{selected.customerEmail}</p></div><p className="whitespace-pre-wrap text-sm">{selected.description}</p><textarea value={reply} onChange={(e) => setReply(e.target.value)} placeholder="Reply to customer" className="mt-6 min-h-28 w-full rounded-lg border p-3"/><button onClick={sendReply} className="btn-primary mt-3">Send reply</button></> : <p className="text-sm text-gray-500">Select a message to view and reply.</p>}</div></div></div>
}
