"use client"
import { useEffect, useState } from "react"
const statuses = ["ALL", "PENDING", "PROCESSING", "SHIPPED", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED"]
export default function AdminDeliveriesPage() {
	const [status, setStatus] = useState("ALL"); const [deliveries, setDeliveries] = useState<any[]>([]); const [error, setError] = useState("")
	const load = () => fetch(`/api/admin/deliveries?status=${status}`, { cache: "no-store" }).then((r) => r.ok ? r.json() : Promise.reject(new Error("Unable to load deliveries"))).then((data) => setDeliveries(data.deliveries || [])).catch((e) => setError(e.message))
	useEffect(() => { load() }, [status])
	const update = async (id: string, next: string) => { const response = await fetch(`/api/admin/deliveries/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: next }) }); if (!response.ok) setError("Unable to update delivery"); else load() }
	return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Deliveries</h1><p className="mt-1 text-gray-500">Track and update delivery status from live orders.</p></div>{error && <p className="text-sm text-red-500">{error}</p>}<div className="flex flex-wrap gap-2">{statuses.map((item) => <button key={item} onClick={() => setStatus(item)} className={`rounded-lg px-3 py-2 text-xs ${status === item ? "bg-primary text-white" : "border"}`}>{item.replaceAll("_", " ")}</button>)}</div><div className="glass-card overflow-x-auto"><table className="w-full min-w-[820px]"><thead><tr className="border-b text-left text-sm text-gray-500"><th className="p-4">Order</th><th className="p-4">Customer</th><th className="p-4">Destination</th><th className="p-4">Items</th><th className="p-4">Tracking</th><th className="p-4">Status</th><th className="p-4"/></tr></thead><tbody>{deliveries.map((delivery) => { const address = delivery.shippingAddress || {}; return <tr key={delivery.id} className="border-b last:border-0"><td className="p-4 font-mono text-sm">#{delivery.id.slice(-8).toUpperCase()}</td><td className="p-4">{delivery.customer}<p className="text-xs text-gray-500">{delivery.user?.email || address.email}</p></td><td className="p-4 text-sm">{address.town}, {address.county}</td><td className="p-4">{delivery.itemCount}</td><td className="p-4 text-sm">{delivery.trackingNumber || "—"}</td><td className="p-4"><select value={delivery.status} onChange={(e) => update(delivery.id, e.target.value)} className="rounded border px-2 py-1 text-xs">{statuses.filter((item) => item !== "ALL").map((item) => <option key={item}>{item}</option>)}</select></td><td className="p-4 text-sm">KES {delivery.total.toLocaleString()}</td></tr>})}</tbody></table>{!deliveries.length && <p className="p-10 text-center text-gray-500">No deliveries found.</p>}</div></div>
}
