"use client"

import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { Search, Save, Trash2 } from "lucide-react"

type Product = { id: string; name: string; slug: string; brand: string; price: number; discountedPrice?: number | null; stock: number; images: string[]; category?: { name: string }; reviewCount?: number }

export default function AdminProductsPage() {
	const [products, setProducts] = useState<Product[]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [editing, setEditing] = useState<string | null>(null)
	useEffect(() => { fetch("/api/products?limit=100").then(async (response) => { if (!response.ok) throw new Error("Unable to load products"); return response.json() }).then((data) => setProducts(data.products)).catch((reason) => setError(reason.message)) }, [])
	const filtered = useMemo(() => products.filter((product) => `${product.name} ${product.brand} ${product.category?.name || ""}`.toLowerCase().includes(query.toLowerCase())), [products, query])
	if (error) return <div className="py-20 text-center text-red-500">{error}</div>
	const save = async (product: Product) => { const response = await fetch(`/api/products/${product.slug}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ price: product.price, discountedPrice: product.discountedPrice, stock: product.stock }) }); if (!response.ok) setError("Unable to save product"); else setEditing(null) }
	const remove = async (product: Product) => { if (!window.confirm(`Delete ${product.name}?`)) return; const response = await fetch(`/api/products/${product.slug}`, { method: "DELETE" }); if (!response.ok) { const body = await response.json(); setError(body.message || "Unable to delete product") } else setProducts((items) => items.filter((item) => item.id !== product.id)) }
	return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Products</h1><p className="mt-1 text-gray-500">Live catalog inventory and CRUD controls.</p></div><div className="glass-card flex items-center gap-3 p-4"><Search className="text-gray-400" size={18}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products" className="w-full bg-transparent outline-none"/></div>{error && <p className="text-sm text-red-500">{error}</p>}<div className="glass-card overflow-x-auto"><table className="w-full min-w-[860px]"><thead><tr className="border-b text-left text-sm text-gray-500"><th className="p-4">Product</th><th className="p-4">Category</th><th className="p-4">Price</th><th className="p-4">Sale price</th><th className="p-4">Stock</th><th className="p-4">Reviews</th><th className="p-4"/></tr></thead><tbody>{filtered.map((product) => <tr key={product.id} className="border-b last:border-0"><td className="p-4"><p className="font-medium">{product.name}</p><p className="text-xs text-gray-500">{product.brand} · {product.slug}</p></td><td className="p-4 text-sm">{product.category?.name || "—"}</td><td className="p-4">{editing === product.id ? <input type="number" value={product.price} onChange={(e) => setProducts((items) => items.map((item) => item.id === product.id ? { ...item, price: Number(e.target.value) } : item))} className="w-28 rounded border px-2 py-1"/> : `KES ${product.price.toLocaleString()}`}</td><td className="p-4">{editing === product.id ? <input type="number" value={product.discountedPrice ?? ""} onChange={(e) => setProducts((items) => items.map((item) => item.id === product.id ? { ...item, discountedPrice: e.target.value ? Number(e.target.value) : null } : item))} className="w-28 rounded border px-2 py-1"/> : product.discountedPrice ? `KES ${product.discountedPrice.toLocaleString()}` : "—"}</td><td className="p-4">{editing === product.id ? <input type="number" min="0" value={product.stock} onChange={(e) => setProducts((items) => items.map((item) => item.id === product.id ? { ...item, stock: Number(e.target.value) } : item))} className="w-20 rounded border px-2 py-1"/> : product.stock}</td><td className="p-4">{product.reviewCount ?? 0}</td><td className="p-4"><div className="flex items-center gap-2">{editing === product.id ? <button onClick={() => save(product)} aria-label="Save product"><Save size={17} className="text-green-600"/></button> : <button onClick={() => setEditing(product.id)} className="text-sm text-primary">Edit</button>}<Link href={`/products/${product.slug}`} className="text-sm text-primary">View</Link><button onClick={() => remove(product)} aria-label="Delete product" className="text-red-500"><Trash2 size={17}/></button></div></td></tr>)}</tbody></table>{!filtered.length && <p className="p-10 text-center text-gray-500">No products found.</p>}</div></div>
}
