import InfoPage from "@/components/content/InfoPage"
import { getStoreContext } from "@/lib/store-context.server"

export default async function TermsPage() {
	const store = await getStoreContext()
	if (store.isPlatformHome) {
		return <InfoPage title="Merchant Platform Terms" description="Merchant Platform Terms, version merchant-terms-v1. These terms apply when a merchant creates and operates a store on Nurava Tech." sections={[
			{ title: "Using the platform", content: "Merchants must provide accurate business and account information, keep login credentials secure, and use Nurava Tech only for lawful business activity. A merchant is responsible for its store content, catalogue, customer communications, and compliance obligations." },
			{ title: "Platform services and billing", content: "Nurava Tech provides store discovery, hosting, storefront technology, merchant tools, and platform support. The selected plan, one-time setup fee, subscription charges, included limits, and paid add-ons are shown during onboarding or in the merchant workspace. Platform billing is for Nurava Tech services and is not payment for a shopper's product order." },
			{ title: "Billing, renewals, and M-Pesa", content: "Nurava Tech subscriptions are billed monthly in Kenyan Shillings (KES). New stores begin with a six-month free Founding Merchant pilot on Starter limits; afterwards the one-time setup fee and first monthly subscription are collected together when the merchant chooses a plan. M-Pesa requests are initiated to the merchant's phone and completed with the merchant's M-Pesa PIN; they are not automatic recurring debits. Renewals and add-on charges create an invoice and are paid only after provider confirmation into Nurava Tech's registered PayBill. A 14-day grace period applies to due payments. Live collection is available only after the Nurava Tech business identity and PayBill registration are complete." },
			{ title: "Taxes and invoices", content: "Nurava Tech's agreed SaaS pricing policy is VAT-inclusive. Where VAT applies and is enabled for the registered business, the subscription, setup fee, and paid add-on prices include 16% VAT. The invoice shows the applicable rate, net amount, VAT amount, account credit, and final amount due. Tax registration and service classification determine when VAT is charged." },
			{ title: "Cancellation, refunds, and service credits", content: "A voluntary cancellation does not create a routine subscription refund; access continues through the paid period. Refunds are limited to duplicate payments, billing errors, or cases required by law. The setup fee is refundable only if Nurava Tech cannot provision the store before setup work begins; it is non-refundable after setup work starts. A verified Nurava Tech or core-hosting outage lasting at least 24 continuous hours creates an account credit for paid plans: one day of recurring monthly subscription value for each complete 24-hour period, capped at one monthly subscription fee. Credits apply to future subscription invoices and not to setup fees. Planned maintenance, merchant-side internet or device failures, force majeure, and optional third-party service failures are excluded." },
			{ title: "Merchant sales responsibility", content: "Each independent merchant is the seller of its products and controls availability, prices, delivery, refunds, replacements, warranties, taxes, and customer support. Nurava Tech connects merchants and shoppers and provides technology; it does not become the merchant of record for products listed by independent stores." },
			{ title: "Data retention and deletion", content: "After paid access ends, merchant workspace data is retained for 90 days and then deleted or anonymized. Closed shopper enquiries and contact details are retained for 12 months after the last interaction while the workspace remains active. Sensitive verification files are deleted 90 days after the final decision or account end, whichever is later. SaaS billing, invoice, payment, refund or credit, audit, and legal-acceptance records are retained for 7 years, unless a legal hold or applicable law requires longer." },
			{ title: "Version changes and acceptance", content: "The current merchant terms version is recorded when a merchant accepts the terms. Material changes receive at least 30 days' notice and apply to an existing merchant at renewal; the merchant remains on the accepted version until then. Urgent security or legal changes may require earlier acceptance. Minor formatting or typo corrections do not by themselves require a new version." },
			{ title: "Access, support, and suspension", content: "Merchants can contact Nurava Tech about platform access, hosting, billing, or technical support. We may limit or suspend platform access for non-payment, security risks, unlawful activity, or material misuse, while the merchant remains responsible for resolving its customer obligations." },
		]} />
	}

	return <InfoPage title="Terms and Conditions" description="The terms that apply when you use this independent store or contact its merchant about a product." sections={[
		{ title: "Using the store", content: "Please provide accurate information, keep your login details secure, and use the store only for lawful purposes. The merchant may suspend access involved in fraud, abuse, or attempts to compromise the service." },
		{ title: "Products and orders", content: "The independent merchant controls product availability, prices, delivery estimates, promotions, order acceptance, and customer communications. Nurava Tech provides the underlying discovery and storefront technology." },
		{ title: "Support, returns, and warranties", content: "The merchant that sells a product is responsible for delivery, refunds, replacements, warranty claims, taxes, and customer support. Contact the merchant directly about a purchase or product issue. Nothing in these terms limits rights that cannot legally be excluded." },
	]} />
}
