"use client"
import { useEffect, useState } from "react"
type SecurityEvent = { id: string; email: string; ipAddress: string | null; success: boolean; createdAt: string }
type AdminAccount = { id: string; name: string | null; email: string; role: string; createdAt: string }
type SecurityData = { events: SecurityEvent[]; admins: AdminAccount[]; stats: { totalLogins: number; successful: number; failed: number; activeAdmins: number } }
const emptySecurityData: SecurityData = { events: [], admins: [], stats: { totalLogins: 0, successful: 0, failed: 0, activeAdmins: 0 } }
export default function AdminSecurityPage() {
	const [data, setData] = useState<SecurityData>(emptySecurityData); const [error, setError] = useState("")
	useEffect(() => { fetch("/api/admin/security", { cache: "no-store" }).then((r) => r.ok ? r.json() as Promise<SecurityData> : Promise.reject(new Error("Unable to load security data"))).then(setData).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load security data")) }, [])
	const stats = [{ label: "Login events", value: data.stats.totalLogins }, { label: "Successful", value: data.stats.successful }, { label: "Failed", value: data.stats.failed }, { label: "Admin accounts", value: data.stats.activeAdmins }]
	return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Security</h1><p className="mt-1 text-gray-500">Database-backed login events and administrator accounts.</p></div>{error && <p className="text-sm text-red-500">{error}</p>}<div className="grid gap-4 sm:grid-cols-4">{stats.map(({ label, value }) => <div key={label} className="glass-card p-4"><p className="text-2xl font-bold">{value}</p><p className="text-sm text-gray-500">{label}</p></div>)}</div><div className="glass-card overflow-x-auto"><h2 className="border-b p-4 font-semibold">Login activity</h2><table className="w-full min-w-[700px]"><thead><tr className="border-b text-left text-sm text-gray-500"><th className="p-4">Email</th><th className="p-4">IP</th><th className="p-4">Result</th><th className="p-4">Time</th></tr></thead><tbody>{data.events.map((event) => <tr key={event.id} className="border-b last:border-0"><td className="p-4">{event.email}</td><td className="p-4 font-mono text-xs">{event.ipAddress || "—"}</td><td className={`p-4 text-sm ${event.success ? "text-green-600" : "text-red-600"}`}>{event.success ? "Success" : "Failed"}</td><td className="p-4 text-sm">{new Date(event.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!data.events.length && <p className="p-10 text-center text-gray-500">No login events recorded yet.</p>}</div><div className="glass-card overflow-x-auto"><h2 className="border-b p-4 font-semibold">Administrators</h2><table className="w-full"><tbody>{data.admins.map((admin) => <tr key={admin.id} className="border-b last:border-0"><td className="p-4">{admin.name || "Unnamed"}<p className="text-xs text-gray-500">{admin.email}</p></td><td className="p-4 text-sm">{admin.role}</td><td className="p-4 text-sm text-gray-500">Created {new Date(admin.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></div>
}
