"use client"
import { useEffect, useState } from "react"
import { Search, Users } from "lucide-react"

export default function AdminCustomersPage() {
	const [search, setSearch] = useState("")
	const [data, setData] = useState<any>({ customers: [], stats: {} })
	const [error, setError] = useState("")
	useEffect(() => { const controller = new AbortController(); fetch(`/api/admin/customers?search=${encodeURIComponent(search)}`, { signal: controller.signal, cache: "no-store" }).then((r) => r.ok ? r.json() : Promise.reject(new Error("Unable to load customers"))).then(setData).catch((e) => { if (e.name !== "AbortError") setError(e.message) }); return () => controller.abort() }, [search])
	return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Customers</h1><p className="mt-1 text-gray-500">Live customer accounts and order value.</p></div>{error && <p className="text-sm text-red-500">{error}</p>}<div className="grid gap-4 sm:grid-cols-4">{[["Total",data.stats.total], ["Active",data.stats.active], ["VIP",data.stats.vip], ["Revenue",`KES ${(data.stats.totalRevenue || 0).toLocaleString()}`]].map(([label,value]) => <div key={label as string} className="glass-card p-4"><Users className="mb-2 text-primary" size={22}/><p className="text-2xl font-bold">{value ?? "—"}</p><p className="text-sm text-gray-500">{label}</p></div>)}</div><div className="glass-card flex items-center gap-3 p-4"><Search className="text-gray-400" size={18}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name or email" className="w-full bg-transparent outline-none" /></div><div className="glass-card overflow-x-auto"><table className="w-full min-w-[700px]"><thead><tr className="border-b text-left text-sm text-gray-500"><th className="p-4">Customer</th><th className="p-4">Status</th><th className="p-4">Orders</th><th className="p-4">Spent</th><th className="p-4">Joined</th><th className="p-4">Last order</th></tr></thead><tbody>{data.customers.map((customer: any) => <tr key={customer.id} className="border-b last:border-0"><td className="p-4"><p className="font-medium">{customer.name || "Unnamed"}</p><p className="text-xs text-gray-500">{customer.email}</p></td><td className="p-4 capitalize">{customer.status}</td><td className="p-4">{customer.totalOrders}</td><td className="p-4">KES {customer.totalSpent.toLocaleString()}</td><td className="p-4 text-sm">{new Date(customer.createdAt).toLocaleDateString()}</td><td className="p-4 text-sm">{customer.lastOrder ? new Date(customer.lastOrder).toLocaleDateString() : "—"}</td></tr>)}</tbody></table>{!data.customers.length && <p className="p-10 text-center text-gray-500">No customers found.</p>}</div></div>
}
