"use client"
import { useEffect, useState } from "react"
import ConfirmDialog from "@/components/ui/ConfirmDialog"
export default function AdminReviewsPage() {
	const [status, setStatus] = useState("ALL"); const [data, setData] = useState<any>({ reviews: [], stats: {} }); const [error, setError] = useState("")
	const [reviewToReject, setReviewToReject] = useState<{ id: string; productName: string } | null>(null)
	const load = () => fetch(`/api/admin/reviews?status=${status}`, { cache: "no-store" }).then((r) => r.ok ? r.json() : Promise.reject(new Error("Unable to load reviews"))).then(setData).catch((e) => setError(e.message))
	useEffect(() => { load() }, [status])
	const moderate = async (id: string, moderationStatus: string) => { const response = await fetch("/api/admin/reviews", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, moderationStatus }) }); if (!response.ok) setError("Unable to update review"); else load() }
	return <div className="space-y-6"><ConfirmDialog open={Boolean(reviewToReject)} title="Reject this review?" description={reviewToReject ? `The review for ${reviewToReject.productName} will be hidden from customers.` : ""} confirmLabel="Reject review" onCancel={() => setReviewToReject(null)} onConfirm={() => { if (!reviewToReject) return; const review = reviewToReject; setReviewToReject(null); void moderate(review.id, "REJECTED") }} /><div><h1 className="text-3xl font-bold">Review moderation</h1><p className="mt-1 text-gray-500">Approve, flag, or reject customer reviews before publication.</p></div>{error && <p className="text-sm text-red-500">{error}</p>}<div className="grid gap-4 sm:grid-cols-4">{[["Total",data.stats.total], ["Pending",data.stats.pending], ["Approved",data.stats.approved], ["Flagged",data.stats.flagged]].map(([label,value]) => <div key={label as string} className="glass-card p-4"><p className="text-2xl font-bold">{value ?? "—"}</p><p className="text-sm text-gray-500">{label}</p></div>)}</div><div className="flex gap-2">{["ALL","PENDING","APPROVED","FLAGGED","REJECTED"].map((item) => <button key={item} onClick={() => setStatus(item)} className={`rounded-lg px-3 py-2 text-xs ${status === item ? "bg-primary text-white" : "border"}`}>{item}</button>)}</div><div className="glass-card overflow-x-auto"><table className="w-full min-w-[800px]"><thead><tr className="border-b text-left text-sm text-gray-500"><th className="p-4">Product</th><th className="p-4">Customer</th><th className="p-4">Rating</th><th className="p-4">Comment</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{data.reviews.map((review: any) => { const reviewTarget = review.product?.name || "Store"; return <tr key={review.id} className="border-b last:border-0"><td className="p-4">{reviewTarget}{!review.product && <span className="ml-2 text-xs text-gray-500">(homepage)</span>}</td><td className="p-4"><p>{review.user.name || "—"}</p><p className="text-xs text-gray-500">{review.user.email}</p></td><td className="p-4">{review.rating}/5</td><td className="max-w-xs p-4 text-sm">{review.comment || "—"}</td><td className="p-4 text-xs">{review.moderationStatus}</td><td className="p-4"><div className="flex gap-2"><button onClick={() => moderate(review.id, "APPROVED")} className="rounded border px-2 py-1 text-xs text-green-600">Approve</button><button onClick={() => moderate(review.id, "FLAGGED")} className="rounded border px-2 py-1 text-xs text-orange-600">Flag</button><button onClick={() => setReviewToReject({ id: review.id, productName: reviewTarget })} className="rounded border px-2 py-1 text-xs text-red-600">Reject</button></div></td></tr> })}</tbody></table>{!data.reviews.length && <p className="p-10 text-center text-gray-500">No reviews in this queue.</p>}</div></div>
}
